[book]
name = "{{project-name}}"
authors = ["{{authors}}"]
title = "Mdbook Template"
description = "An mdbook made using template for cargo-generate"
src = "src"
version = "0.1.0"

[build]
build-dir = "docs"


